development:
  adapter: postgresql
  encoding: unicode
  database: quina_development
  pool: 5
  username: thiago
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: quina_test
  pool: 5
  username: thiago
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: quina_production
  pool: 5
  username: thiago
  password:
